// styles.js - Centralized styles for the Home component

export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#0f0f1a',
    color: '#7A7687',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.75rem 1.5rem',
    backgroundColor: '#ff7e5f',
    background: 'linear-gradient(90deg, #C7C1DB, #9E94BE)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    marginTop: '1.5rem',
  },
  buttonHover: {
    transform: 'translateY(-2px)',
    boxShadow: '0 6px 20px rgba(115, 102, 159, 0.3)',
  },
  buttonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
    background: '#555',
  },
  navbar: {
    width: '100%',
    padding: '1rem 2rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    position: 'sticky',
    top: 0,
    zIndex: 10,
    backgroundColor: '#C7C1DB',
  },
  logoContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  logoText: {
    fontSize: '2rem',
    fontWeight: 'bold',
    background: 'linear-gradient(90deg, #f9b42a, #e7e789)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    margin: 0,
  },
  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  spotifyButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    backgroundColor: '#E7E789',
    color: '#73669F',
    border: 'none',
    borderRadius: '2rem',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontWeight: '600',
    transition: 'all 0.2s ease',
  },
  userProfile: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  userName: {
    fontWeight: '500',
    fontSize: '1rem',
    color: '#7A7687',
  },
  userAvatar: {
    borderRadius: '50%',
    border: '2px solid rgba(255, 255, 255, 0.2)',
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '3rem 1.5rem',
    backgroundColor: '#FFFFF2',
  },
  inputContainer: {
    width: '100%',
    maxWidth: '800px',
    marginTop: '1rem',
  },
  promptInput: {
    width: '100%',
    padding: '1.25rem',
    fontSize: '1.125rem',
    backgroundColor: 'rgba(0, 0, 255, 0.05)',
    color: '#7A7687',
    border: '1px solid rgba(0, 0, 255, 0.1)',
    borderRadius: '12px',
    outline: 'none',
    transition: 'all 0.3s ease',
  },
  promptInputFocus: {
    border: '1px solid rgba(115, 102, 159, 0.5)',
    boxShadow: '0 0 0 4px rgba(115, 102, 159, 0.1)',
  },
  promptLabel: {
    display: 'block',
    marginBottom: '0.75rem',
    fontSize: '1.125rem',
    fontWeight: '500',
  },
  title: {
    margin: 0,
    lineHeight: 1.15,
    fontSize: '2.5rem',
    textAlign: 'center',
    background: 'linear-gradient(135deg, #f6b127, #E7C889, #E7E789, #e5e53a)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    padding: '0.5rem 0',
  },
  description: {
    textAlign: 'center',
    lineHeight: '1.5',
    fontSize: '1.25rem',
    margin: '1rem 0 2rem 0',
    opacity: 0.9,
    maxWidth: '600px',
  },
  error: {
    color: '#ff5555',
    marginBottom: '1.5rem',
    padding: '0.75rem 1.5rem',
    backgroundColor: 'rgba(255, 85, 85, 0.1)',
    borderRadius: '8px',
    borderLeft: '4px solid #ff5555',
    maxWidth: '800px',
    width: '100%',
  },
  switchesContainer: {
    width: '100%',
    maxWidth: '800px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  switchRow: {
    display: 'flex',
    flexDirection: 'column',
    width: 'calc(50% - 0.5rem)',
    padding: '0.75rem 1rem',
    backgroundColor: 'rgba(0, 0, 255, 0.05)',
    borderRadius: '8px',
  },
  switchLabel: {
    fontWeight: '500',
    fontSize: '0.875rem',
    marginBottom: '0.5rem',
    color: 'rgba(122, 118, 135, 0.8)',
  },
  // Toggle button styles
  toggleButton: {
    position: 'relative',
    width: '120px',
    height: '30px',
    borderRadius: '15px',
    background: 'rgba(30, 30, 45, 0.5)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    padding: '0 4px',
    overflow: 'hidden',
  },
  toggleButtonActive: {
    background: 'linear-gradient(90deg, #E8E6F0, #73669F)',
    borderColor: 'rgba(115, 102, 159, 0.2)',
    boxShadow: '0 0 10px rgba(115, 102, 159, 0.3)',
  },
  toggleButtonInactive: {
    background: 'linear-gradient(90deg, #FFF4DD, #E7C889)',
    borderColor: 'rgba(231, 200, 137, 0.1)',
    boxShadow: '0 0 10px rgba(231, 200, 137, 0.2)',
  },
  toggleSlider: {
    position: 'absolute',
    width: '22px',
    height: '22px',
    borderRadius: '50%',
    backgroundColor: 'white',
    transition: 'transform 0.3s ease, background-color 0.3s ease, box-shadow 0.3s ease',
    transform: 'translateX(0)',
    boxShadow: '0 2px 5px rgba(0, 0, 0, 0.2)',
  },
  toggleSliderActive: {
    transform: 'translateX(90px)',
    backgroundColor: '#ffffff',
    boxShadow: '0 0 8px rgba(255, 255, 255, 0.5)',
  },
  toggleSliderInactive: {
    transform: 'translateX(0)',
    backgroundColor: '#ffffff',
    boxShadow: '0 0 8px rgba(255, 255, 255, 0.3)',
  },
  toggleText: {
    position: 'absolute',
    width: '100%',
    textAlign: 'center',
    fontSize: '0.8rem',
    fontWeight: 'bold',
    transition: 'opacity 0.3s ease',
    color: 'rgba(255, 255, 255, 0.8)',
    opacity: 0.9,
    userSelect: 'none',
  },
  toggleTextOn: {
    right: '20px',
    color: 'white',
    textShadow: '0 0 4px rgba(0, 0, 0, 0.3)',
  },
  toggleTextOff: {
    left: '20px',
    color: 'rgba(255, 255, 255, 0.9)',
    textShadow: '0 0 4px rgba(0, 0, 0, 0.3)',
  },
  optionLabel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '0.5rem',
  },
  settingsSection: {
    width: '100%',
    maxWidth: '800px',
    marginBottom: '2rem',
  },
  sectionTitle: {
    fontSize: '1.25rem',
    fontWeight: '600',
    marginBottom: '1rem',
    width: '100%',
    maxWidth: '800px',
  },
  customizeInputContainer: {
    width: 'calc(50% - 0.5rem)',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '8px',
    padding: '0.75rem 1rem',
  },
  customInput: {
    padding: '0.5rem 0.75rem',
    fontSize: '0.875rem',
    backgroundColor: 'rgba(115, 102, 159, 0.2)',
    color: '#7A7687',
    border: '1px solid rgba(199, 193, 219, 0.1)',
    borderRadius: '20px',
    outline: 'none',
    transition: 'all 0.3s ease',
  },
  customInputFocus: {
    border: '1px solid rgba(115, 102, 159, 0.5)',
    boxShadow: '0 0 0 3px rgba(115, 102, 159, 0.1)',
  },
  // Top tracks section styles
  topTracksSection: {
    width: '100%',
    maxWidth: '800px',
    marginTop: '2rem',
    backgroundColor: 'rgba(0, 0, 255, 0.05)',
    borderRadius: '12px',
    padding: '1.5rem',
  },
  tracksList: {
    listStyle: 'none',
    padding: 0,
    margin: '1rem 0 0 0',
  },
  trackItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '0.75rem 0',
    borderBottom: '1px solid rgba(115, 102, 159, 0.1)',
  },
  trackItemHover: {
    transform: 'scale(1.05)',
    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.1)',
  },
  trackNumber: {
    width: '30px',
    fontSize: '1rem',
    fontWeight: '600',
    color: 'rgba(122, 118, 135, 0.7)',
  },
  trackImage: {
    borderRadius: '4px',
    marginRight: '1rem',
  },
  trackInfo: {
    flex: 1,
  },
  trackName: {
    fontSize: '1rem',
    fontWeight: '600',
    marginBottom: '0.25rem',
  },
  trackArtist: {
    fontSize: '0.875rem',
    color: 'rgba(122, 118, 135, 0.7)',
  },
  loadingIndicator: {
    textAlign: 'center',
    padding: '1rem',
    color: 'rgba(122, 118, 135, 0.7)',
  },
  // Recommendations section styles
  recommendationsSection: {
    width: '100%',
    maxWidth: '800px',
    marginTop: '2rem',
    backgroundColor: 'rgba(0, 0, 255, 0.05)',
    borderRadius: '12px',
    padding: '1.5rem',
  },
  storyText: {
    fontStyle: 'italic',
    marginBottom: '1.5rem',
    padding: '1rem',
    borderRadius: '8px',
    backgroundColor: 'rgba(158, 148, 190, 0.2)',
    lineHeight: '1.6',
  },
  recommendationsList: {
    listStyle: 'none',
    padding: 0,
    margin: '1rem 0 0 0',
  },
  playlistInfo: {
    marginTop: '1.5rem',
    padding: '1rem',
    backgroundColor: 'rgba(29, 185, 84, 0.1)',
    borderRadius: '8px',
    border: '1px solid rgba(29, 185, 84, 0.3)',
  },
  playlistTitle: {
    fontSize: '1.1rem',
    fontWeight: '600',
    marginBottom: '0.5rem',
  },
  playlistLink: {
    color: '#1DB954',
    textDecoration: 'none',
    fontWeight: '500',
    display: 'inline-block',
    marginTop: '0.5rem',
  },
  // Audio features and insights styles
  trackDetails: {
    padding: '0.75rem',
    backgroundColor: 'rgba(0, 0, 255, 0.02)',
    borderRadius: '8px',
    marginTop: '0.5rem',
    marginRight: '1rem',
    overflow: 'hidden',
    maxHeight: '0',
    transition: 'max-height 0.3s ease, padding 0.3s ease',
  },
  trackDetailsOpen: {
    maxHeight: '1000px',
    padding: '0.75rem',
  },
  detailsButton: {
    background: 'none',
    border: 'none',
    color: 'rgba(115, 102, 159, 0.6)',
    fontSize: '0.75rem',
    cursor: 'pointer',
    padding: '0.25rem 0.5rem',
    marginLeft: '0.5rem',
    borderRadius: '4px',
  },
  insightsContainer: {
    marginTop: '2rem',
    padding: '1rem',
    backgroundColor: 'rgba(231, 200, 137, 0.1)',
    borderRadius: '8px',
    border: '1px solid rgba(231, 200, 137, 0.3)',
  },
  insightTitle: {
    fontSize: '1.1rem',
    fontWeight: '600',
    marginBottom: '1rem',
    color: 'rgba(122, 118, 135, 0.9)',
  },
  insightsList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  insightItem: {
    padding: '0.75rem',
    marginBottom: '0.75rem',
    backgroundColor: 'rgba(231, 200, 137, 0.2)',
    borderRadius: '8px',
    fontSize: '0.9rem',
    lineHeight: '1.5',
  },
  moodFeatures: {
    marginTop: '1rem',
    marginBottom: '1.5rem',
  },
  spotifyListenButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    backgroundColor: '#1DB954',
    color: 'white',
    border: 'none',
    borderRadius: '2rem',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontWeight: '600',
    transition: 'all 0.2s ease',
    textDecoration: 'none',
    marginLeft: '1rem',
  },
  spotifyListenButtonHover: {
    backgroundColor: '#1aa34a',
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 12px rgba(29, 185, 84, 0.3)',
  },
  // Track buttons and actions container styles
  trackButtonsContainer: {
    display: 'flex',
    alignItems: 'center',
    marginLeft: 'auto',
    gap: '0.5rem',
  },
  trackActionsContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '0.5rem',
    marginLeft: 'auto',
  },
  trackMainActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  // Logout button styles
  logoutButton: {
    backgroundColor: 'transparent',
    border: '1px solid rgba(231, 231, 137, 0.3)',
    color: '#E7E789',
    borderRadius: '2rem',
    padding: '0.25rem 0.75rem',
    fontSize: '0.75rem',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  // User avatar placeholder styles
  userAvatarPlaceholder: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: '#1DB954',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 'bold',
  },
  // Feedback container integration styles
  trackWithFeedback: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  trackMainContent: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
  },
  feedbackContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: '0.5rem',
    paddingRight: '1rem',
  }
};